In [ ]:
import numpy as np

# Esempio di matrice delle distanze D (N x N)
# D[i, j] rappresenta dij
D = np.array([
    [0, 10, 15, 20],
    [10, 0,  35, 25],
    [15, 35,  0, 30],
    [20, 25, 30,  0]
])

# Estraiamo i vettori colonna e riga rispetto al deposito (indice 0)
di0 = D[:, 0, np.newaxis]  # Forma (N, 1) - Vettore colonna
d0j = D[0, :, np.newaxis].T  # Forma (1, N) - Vettore riga (oppure semplicemente D[0, :])

# Sfruttiamo il broadcasting per calcolare la matrice mu
mu = di0 + d0j - D

print(mu)

[[  0   0   0   0]
 [  0  20 -10   5]
 [  0 -10  30   5]
 [  0   5   5  40]]


In [3]:
mu = D[:, [0]] + D[0, :] - D
mu

array([[  0,   0,   0,   0],
       [  0,  20, -10,   5],
       [  0, -10,  30,   5],
       [  0,   5,   5,  40]])

In [18]:
D[:,[0]] + D[0,:] - D

array([[  0,   0,   0,   0],
       [  0,  20, -10,   5],
       [  0, -10,  30,   5],
       [  0,   5,   5,  40]])